### ISSUE TITLE
The columns for staff members in the contributor pages are uneven

### ISSUE THREAD

**Issue by lawrencehlee** [lawrencehlee/themq-website#72]

**Comment by lawrencehlee** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Columns for staff members are uneven](https://trello.com/c/X6Up8ocN/122-columns-for-staff-members-are-uneven)

**Comment by BarakTzori** [comment]
Are you sure this isn't just an odd-even issue? You know where one column has one more staff member than the other
